force-app/main/default/objects/PLR_UI_Log__c/PLR_UI_Log__c.object-meta.xml
<CustomObject>
    <description>PLR custom UI event log</description>
    <label>PLR UI Log</label>
    <nameField>
        <displayFormat>UIL-{00000000}</displayFormat>
        <label>PLR UI Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PLR UI Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PLR_UI_Log__c/fields/Component__c.field-meta.xml
<CustomField>
    <fullName>Component__c</fullName>
    <label>Component</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PLR_UI_Log__c/fields/Guid__c.field-meta.xml
<CustomField>
    <fullName>Guid__c</fullName>
    <label>Guid</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PLR_UI_Log__c/fields/IP_Address__c.field-meta.xml
<CustomField>
    <fullName>IP_Address__c</fullName>
    <label>IP Address</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PLR_UI_Log__c/fields/Link_Label__c.field-meta.xml
<CustomField>
    <fullName>Link_Label__c</fullName>
    <label>Link Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PLR_UI_Log__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PLR_UI_Log__c/fields/Permission_Sets__c.field-meta.xml
<CustomField>
    <fullName>Permission_Sets__c</fullName>
    <label>Permission Sets</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PLR_UI_Log__c/fields/Profile_Name__c.field-meta.xml
<CustomField>
    <fullName>Profile_Name__c</fullName>
    <label>Profile Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PLR_UI_Log__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <label>Record Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PLR_UI_Log__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <label>Route</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PLR_UI_Log__c/fields/Route_Standardised__c.field-meta.xml
<CustomField>
    <fullName>Route_Standardised__c</fullName>
    <label>Route Standardised</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PLR_UI_Log__c/fields/Time_Stamp__c.field-meta.xml
<CustomField>
    <fullName>Time_Stamp__c</fullName>
    <label>Time Stamp</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PLR_UI_Log__c/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <label>User Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Plr_MonitoringPluginCtrl.cls
/* 
 * @author Peter Sewell
 * @date 03/05/2021
 * 
 * @description Used by PLR Utility bar plugin to log PLR data to Object
 * @group Tech Enablers
 */
public without sharing class Plr_MonitoringPluginCtrl {
	@AuraEnabled
	/*
	 * @author Peter Sewell
	 * @date 3/15/2021
	 * @description Posts UI log to custom object
	 * @param aLog the log payload
     * @return true
	 */
	public static Boolean doPostToUILog(String aLog) {
		Boolean retval = true;
		String userId; 
		String profileName; 
		String permissionSets; 
		String guid; 
		String route; 
		String routeStandardised; 
		String ipAddress; 
		Long timeStamp; 
		String component;
		String linkLabel; 
		String recordId;

		List<PLR_UI_Log__c> logFile = new List<PLR_UI_Log__c>();

		try{
			// system.debug(aLog);
			Map<String,Object> logParsed = (Map<String,Object> ) JSON.deserializeUntyped(aLog);
			route = (String) logParsed.get('route');
			// Dont log the UI log!
			if (route.contains('PLR_UI_Log__c')) {
				return retval;
			}
			guid = (String) logParsed.get('guid');
			userId = (String) logParsed.get('userId');
			profileName = (String) logParsed.get('profileName');
			permissionSets = (String) logParsed.get('permissionSets');
			routeStandardised = (String) logParsed.get('routeStandardised');
			ipAddress = (String) logParsed.get('ipAddress');
			timeStamp = (Long) logParsed.get('timeStamp');

			System.debug('guid = ' + guid);
			System.debug('userId = ' + userId);
			System.debug('profileName = ' + profileName);
			System.debug('permissionSets = ' + permissionSets);
			System.debug('route = ' + route);
			System.debug('routeStandardised = ' + routeStandardised);
			System.debug('ipAddress = ' + ipAddress);
			System.debug('timeStamp = ' + timeStamp);
			System.debug('---------------------------------------------');

			List<Object> logRows = (List<Object>) logParsed.get('uiLogRows');
			for(Object logRow : logRows){
				Map<String,Object> row = (Map<String,Object>)logRow;
				component = (String) row.get('component');
				linkLabel = (String) row.get('linkLabel');
				recordId = (String) row.get('recordId');

				// Add record to log object
				PLR_UI_Log__c logRecord = new PLR_UI_Log__c();
				logRecord.Component__c = component;
				logRecord.Guid__c = guid;
				logRecord.IP_Address__c = ipAddress;
				logRecord.Link_Label__c = linkLabel;
				logRecord.Permission_Sets__c = permissionSets;
				logRecord.Profile_Name__c = profileName;
				logRecord.Record_Id__c = recordId;
				Id r = recordId;
				logRecord.Object__c = r.getSObjectType().getDescribe().getName();
				logRecord.Route__c = route;
				logRecord.Route_Standardised__c = routeStandardised;
				logRecord.Time_Stamp__c = timeStamp;
				logRecord.User_Id__c = userId;
				logFile.add(logRecord);

				System.debug('component = ' + component);
				System.debug('linkLabel = ' + linkLabel);
				System.debug('recordId = ' + recordId);
				System.debug('---------------------------------------------');
			}
			if (!logFile.isEmpty()) {
				insert logFile;
			}
		}catch(Exception e){
			throw new AuraHandledException(e.getMessage());
		}
		return retval;
	}
}